### ISSUE TITLE
np.float in response.py no longer supported

### ISSUE THREAD

**Issue by znasipak** [mikekatz04/lisa-on-gpu#1]
It seems that as of Numpy>=1.24, `np.float` is no longer a supported type. The file `reponse.py` creates three `np.zeros` with this type. For those with newer versions of numpy, this code will not compile, so it might be worth changing the `np.float` to `float` or one of the numpy types `np.float32` or `np.float64`

**Comment by mikekatz04** [comment]
Fixed, thanks!
