### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by sphericalharmonics** [mikekatz04/lisa-on-gpu#2]
Hello

I am trying to use this package to get SNRs of 5PNAAK waveforms in the FastEMRIWaveform package with TDI response for multiple EMRI sources in a catalog. My implementation of the response wrapper is as follows:

```
#initialization
TDI_channels = ['TDIA','TDIE','TDIT'] 

N_channels = 3 

index_lambda = 8

index_beta = 7 

t0 = 20000. #20000.0 /40000.0 # How many samples to remove from start and end of simulations 

order = 25 

tdi_gen = "1st generation" 

orbit_file_esa = ".../lisa-on-gpu/orbit_files/esa-trailing-orbits.h5" 

orbit_kwargs_esa = dict(orbit_file=orbit_file_esa) 

tdi_kwargs_esa = dict( 

orbit_kwargs=orbit_kwargs_esa, order=order, tdi=tdi_gen, tdi_chan="AET",

) 

EMRI_TDI = ResponseWrapper(wave_generator,T,dt, 

index_lambda,index_beta,t0=t0, 

flip_hx = True, use_gpu = use_gpu, is_ecliptic_latitude=False, 

remove_garbage = "zero", **tdi_kwargs_esa)

#execution
waveform = EMRI_TDI(M, mu, a, p0, e0, Y0, dist, qS, phiS, qK, phiK, Phi_phi0, Phi_theta0, Phi_r0) 
 
```
I am trying to run this for a bunch of sources. While it runs fine for some, for one particular source, I get an "AssertionError": assert len(inpuit_in) >= self.num_pts

Please help me understand this error and how to fix it.

**Comment by mikekatz04** [comment]
Hey Shubam, so sorry I never responded. Did you get this fixed?
