### ISSUE TITLE
How to use analytical orbit?

### ISSUE THREAD

**Issue by gyy0592** [mikekatz04/lisa-on-gpu#3]
If I want to calculate TDI for analytical orbit, generating numerical orbit form then using the code will cause some overhead. Does this one support analytical orbit? I think there's some code being commented aiming toward that.

**Comment by j2bbayle** [comment]
As far as I know, this only supports numerical orbits (time series of arm lengths).

**Comment by mikekatz04** [comment]
This is true. It is now interfaced with the output of LISA Orbits.
